sudo: required
dist: trusty
language: cpp
compiler: gcc

env:
    - QT=4

install:
    - sudo apt-get update -qq
    - if [ "$QT" = "4" ]; then sudo apt-get install -qq libqt4-dev qt4-qmake qt4-default; fi

script:
    - nproc
    - qmake -v -qt=${QT} shrimp.pro
    - make -j$(nproc)

notifications:
    email: false

